version: '3.8'

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: beam
      POSTGRES_PASSWORD: root
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - '5432:5432'